language: java
jdk: openjdk15

# Cache for speeding up the building
cache:
  directories:
    - $HOME/.m2

before_script:
  - openssl aes-256-cbc -K $encrypted_df60101c7b71_key -iv $encrypted_df60101c7b71_iv -in config/telegram.conf.enc -out config/telegram.conf

branches:
  only:
    - master
