language: java
jdk: openjdk15

# Cache for speeding up the building
cache:
  directories:
    - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_c4f0a139c26a_key -iv $encrypted_c4f0a139c26a_iv -in config/telegram.conf.enc -out config/telegram.conf -d
  - rm config/telegram.conf.enc

branches:
  only:
    - master
