language: java
jdk: openjdk15

# Cache for speeding up the building
cache:
  directories:
    - $HOME/.m2

before_script:
  - cp config/telegram-example.conf config/telegram.conf

branches:
  only:
    - master
