version: '3.8'
services:

  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: monro
      POSTGRES_PASSWORD: root_password
      POSTGRES_USER: root_user
    ports:
      - '5435:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_ADDRESS: db:5432/monro
      DB_PASSWORD: root_password
      DB_USER: root_user
      TELEGRAM_BOT_NAME: bot_name
      TELEGRAM_BOT_TOKEN: bot_token
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  dbdata:
