application:
  security:
    root:
      name: ${ADMIN_NAME:root}
      password: ${ADMIN_PASSWORD:root}

spring:
  application:
    name: Monro consulting bot
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost:5432/monro}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  flyway:
    create-schemas: true
    default-schema: monro
    enabled: true
    locations: classpath:db/migration
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    validate-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Validation does not work if no database platform set explicitly
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  sql:
    init:
      mode: never

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
