spring:
  datasource:
    url: jdbc:hsqldb:file:db/monro
    username: sa
    password: password
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate # Checks that existing schema are fitted for existing entities
  sql:
    init:
      mode: never
      schema-locations: schema.sql, init.sql

server:
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
