spring:
  datasource:
    url: jdbc:h2:mem:monro
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none # For DB initialization only with schema.sql and init.sql
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql

server:
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
